version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
    networks:
      - claude-network

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - app
    networks:
      - claude-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - claude-network

  sqlite:
    image: alpine:latest
    volumes:
      - ./data:/data
    networks:
      - claude-network

volumes:
  redis_data:

networks:
  claude-network:
    driver: bridge
